<a href="https://colab.research.google.com/github/MinhPhuong41/DL1/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
pip install scikeras

In [16]:
my_list = [1, 9, 15, 39]
print(my_list)
my_number_arry = np.array(my_list)
print(my_number_arry)

[1, 9, 15, 39]
[ 1  9 15 39]


In [17]:
c = np.array([(1, 2, 3),
              (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [18]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [19]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n',e)
print('One matrix: \n',f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print(g)
print(g.shape)
h = g.reshape(3,4)
print('reshape (3,4)\n', h)
j = g.reshape(3,2,2)
print('reshape (3,2,2)\n', j)
k = g.reshape(2,3,2)
print('reshape (2,3,2)\n', j)


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [21]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [22]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print(h_stack)
v_stack = np.vstack((f, g))
print(v_stack)


[1. 2. 3. 4. 5. 6.]
[[1. 2. 3.]
 [4. 5. 6.]]


In [23]:
a = np.random.randint(100, size=(5,))
print('Random 1-D arry\n',a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D arry\n',b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D arry\n',c)

Random 1-D arry
 [96 57 41 14 32]
Random 2-D arry
 [[63 77 37 64]
 [66 40 66 37]
 [42 94 17 46]]
Random 3-D arry
 [[[92 62 40]
  [46 81 27]
  [71 55 18]
  [79  6 53]]

 [[40 25 63]
  [ 7  9 16]
  [24 57 87]
  [31 38 93]]

 [[61 17 71]
  [98 18 86]
  [53  0 25]
  [12 63 12]]]


In [24]:
a = np.random.rand(5)
print('Random 1-D arry\n',a)
b = np.random.rand(3, 4)
print('Random 2-D arry\n',b)
c = np.random.rand(3, 4, 3)
print('Random 3-D arry\n',c)

Random 1-D arry
 [0.902941   0.46961351 0.68601764 0.8853434  0.09781747]
Random 2-D arry
 [[0.92023132 0.3573719  0.47880372 0.94499917]
 [0.88572318 0.67606195 0.73484461 0.02347551]
 [0.14546442 0.69582406 0.11746854 0.19041317]]
Random 3-D arry
 [[[0.04791365 0.38062729 0.31601673]
  [0.89809026 0.42324818 0.15389157]
  [0.46298774 0.37918619 0.46762083]
  [0.09486831 0.96758377 0.51928233]]

 [[0.69677146 0.28363557 0.38353186]
  [0.44244772 0.80485096 0.47329135]
  [0.84314012 0.54840946 0.76214602]
  [0.41436683 0.6382125  0.46288086]]

 [[0.55069771 0.60410955 0.70828116]
  [0.48241202 0.29156797 0.31145691]
  [0.6468357  0.63859026 0.68219531]
  [0.13001073 0.79289309 0.6812696 ]]]


In [25]:
a  = np.random.normal(5, 0.5, 10)
print(a)

[4.84084321 5.27094489 4.78190341 4.96259695 4.4412366  4.19103153
 4.20537103 5.68043561 4.71577568 4.48693743]


In [26]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)


6
[[12  4 14 10 20]
 [ 6 20 10  6 12]
 [20  2  2  4 18]]


In [27]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n',A)
np.array(A)[2] = 2
print('Third row with arry\n', A)
np.asarray(A)[2] = 2
print('Third row with asarry\n', A)


The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Third row with arry
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Third row with asarry
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
a = np.arange(1, 20)
print(a)
b = np.arange(1, 20, 2)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [29]:
a = np.linspace(1., 5., num=10)
print(a)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [30]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
print('second column:', a[:,1])
print('first column:', a[:,0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


In [31]:
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [33]:
h = np.array([[1, 2], [3,4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n',df_h)
numpy_h = np.array(df_h)
print('Numpy array:\n',numpy_h)



DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [34]:
dic = {'Name':['John','Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [35]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3','so4'])
print(df.head())

        so1       so2       so3       so4
0  1.182687  0.722065  0.632150 -0.149598
1  0.516296  0.271113 -0.799933 -0.072063
2  1.827240  0.770846 -1.011319  0.313287
3 -0.982401 -0.217781 -1.393198  0.222371
4 -0.872234  0.632859  0.784797 -0.465182


In [36]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3','so4'])
print(df.head())
print("Cot so1\n",df['so1'])
print("Nhieu dong\n",df[0:3])
print("Nhieu cot\n",df[['so1','so3']])
print("Nhieu dong, nhieu cot\n", df.iloc[:3, :2])
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -0.395577 -0.441882  0.809393  1.417859
1 -1.497740  0.920665  0.455542  0.553162
2  2.767426 -0.347273 -1.093206  0.723567
3  0.287934  0.736560  0.355219 -0.441230
4 -0.714782  0.907968 -1.687142 -0.201628
Cot so1
 0    -0.395577
1    -1.497740
2     2.767426
3     0.287934
4    -0.714782
5    -0.070553
6    -0.192891
7     0.627223
8    -0.030710
9    -0.794484
10    2.148148
11   -2.649235
12   -0.140318
13   -1.416224
14   -0.349059
15   -1.400451
16   -0.479229
17   -0.694427
18   -0.633385
19    0.694490
Name: so1, dtype: float64
Nhieu dong
         so1       so2       so3       so4
0 -0.395577 -0.441882  0.809393  1.417859
1 -1.497740  0.920665  0.455542  0.553162
2  2.767426 -0.347273 -1.093206  0.723567
Nhieu cot
          so1       so3
0  -0.395577  0.809393
1  -1.497740  0.455542
2   2.767426 -1.093206
3   0.287934  0.355219
4  -0.714782 -1.687142
5  -0.070553 -0.311960
6  -0.192891 -0.035029
7   0.627223  0.961290
8  -0.030710 -1

In [37]:
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]}, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]}, index=[3, 4])
df_concat = pd.concat([df1, df2])
print(df_concat)
#Xoa Name trung
print(df_concat.drop_duplicates('Name'))
#Sap xep theo cot Age
print(df_concat.sort_values('Age'))
#Doi ten cot
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print(df_rename)

    Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
    Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
    Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
  Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [42]:
path = '/content/sample_data/salary_data.csv'
COLUMNS = ['YearsExperience', 'Salary']
df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)
df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)


   YearsExperience    Salary
0  YearsExperience    Salary
1              1.1  39343.00
2              1.3  46205.00
3              1.5  37731.00
4              2.0  43525.00
(31, 2)
   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
(30, 2)


In [43]:
path = '/content/sample_data/Fish.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())
print(df_csv.groupby(['Species']).mean().head())
print(df_csv.groupby(['Species'])['Weight'].min().head())
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
             Weight    Length1    Length2    Length3     Height     Width
Species                                                                  
Bream    617.828571  30.305714  33.108571  38.354286  15.183211  5.427614
Parkki   154.818182  18.727273  20.345455  22.790909   8.962427  3.220736
Perch    382.239286  25.735714  27.892857  29.571429   7.861870  4.745723
Pike     718.705882  42.476471  45.482353  48.717647   7.713771  5.086382
Roach    152.050000  20.645000  22.275000  24.970000   6.694795  3.657850
Species
Bream     242.0
Parkki     55.0
Perch       5.9
Pike      200.0
Roach       0.0
Name: Weight, dtype: f

In [ ]:
#1
arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên 3x3:")
print(arr)
print("-" * 30)
check_nonzero = np.all(arr != 0)
print("Tất cả các phần tử có khác 0 không:", check_nonzero)

Mảng ngẫu nhiên 3x3:
[[20 13  3]
 [ 0 19  8]
 [12  7  9]]
------------------------------
Tất cả các phần tử có khác 0 không: False


In [ ]:
#2
arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên 3x3:")
print(arr)
print("-" * 30)
check_any_nonzero = np.any(arr != 0)
print("Có phần tử nào khác 0 không:", check_any_nonzero)

Mảng ngẫu nhiên 3x3:
[[11 18  5]
 [15 10  9]
 [10 15 10]]
------------------------------
Có phần tử nào khác 0 không: True


In [ ]:
#3
# --- TRƯỜNG HỢP 1: MẢNG 1 CHIỀU ---
print("--- SO SÁNH MẢNG 1 CHIỀU ---")
a1 = np.array([10, 20, 30, 40])
b1 = np.array([15, 20, 25, 45])
print("Mảng a1: {a1}")
print("Mảng b1: {b1}")
print("a1 > b1  (greater):      ", np.greater(a1, b1))
print("a1 >= b1 (greater_equal):", np.greater_equal(a1, b1))
print("a1 < b1  (less):         ", np.less(a1, b1))
print("a1 <= b1 (less_equal):   ", np.less_equal(a1, b1))
# --- TRƯỜNG HỢP 2: MẢNG 2 CHIỀU (3x3) ---
print("\n--- SO SÁNH MẢNG 2 CHIỀU (3x3) ---")
# Tạo 2 mảng ngẫu nhiên để so sánh
a2 = np.random.randint(0, 10, size=(3, 3))
b2 = np.random.randint(0, 10, size=(3, 3))
print("Mảng a2:\n", a2)
print("Mảng b2:\n", b2)

print("\nKết quả greater (a2 > b2):")
print(np.greater(a2, b2))

print("\nKết quả greater_equal (a2 >= b2):")
print(np.greater_equal(a2, b2))

print("\nKết quả less (a2 < b2):")
print(np.less(a2, b2))

print("\nKết quả less_equal (a2 <= b2):")
print(np.less_equal(a2, b2))


--- SO SÁNH MẢNG 1 CHIỀU ---
Mảng a1: {a1}
Mảng b1: {b1}
a1 > b1  (greater):       [False False  True False]
a1 >= b1 (greater_equal): [False  True  True False]
a1 < b1  (less):          [ True False False  True]
a1 <= b1 (less_equal):    [ True  True False  True]

--- SO SÁNH MẢNG 2 CHIỀU (3x3) ---
Mảng a2:
 [[6 7 0]
 [6 5 2]
 [6 0 4]]
Mảng b2:
 [[3 3 3]
 [2 8 3]
 [3 7 8]]

Kết quả greater (a2 > b2):
[[ True  True False]
 [ True False False]
 [ True False False]]

Kết quả greater_equal (a2 >= b2):
[[ True  True False]
 [ True False False]
 [ True False False]]

Kết quả less (a2 < b2):
[[False False  True]
 [False  True  True]
 [False  True  True]]

Kết quả less_equal (a2 <= b2):
[[False False  True]
 [False  True  True]
 [False  True  True]]


In [ ]:
#4
ones = np.ones(10, dtype=int) # Tạo mảng gồm 10 số 1
zeros = np.zeros(10, dtype=int) # Tạo mảng gồm 10 số 0
fives = np.full(10, 5, dtype=int) # Tạo mảng gồm 10 số 5

# Nối các mảng lại với nhau
combined_array = np.concatenate((zeros , ones, fives))

print(combined_array)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


In [ ]:
#5
even_array = np.arange(30, 71, 2)

print("Mảng số nguyên chẵn từ 30 đến 70:")
print(even_array)

Mảng số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
#6
identity_matrix = np.identity(3)

print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#7
arr = np.random.randint(15, 56, size=10)
print("Mảng đã tạo:")
print(arr)
print("\nCác phần tử (bỏ phần tử đầu và cuối):")
for i in arr[1:-1]:
    print(i, end=" ")

Mảng đã tạo:
[19 42 40 33 31 26 44 36 44 46]

Các phần tử (bỏ phần tử đầu và cuối):
42 40 33 31 26 44 36 44 

In [ ]:
#8
import random
arr = [random.randint(0, 20) for _ in range(20)]

print("Mảng ban đầu:")
print(arr)

for i in range(len(arr)):
    if 9 <= arr[i] <= 15:
        arr[i] = -arr[i]

print("\nMảng sau khi đổi dấu (các số từ 9 đến 15):")
print(arr)

Mảng ban đầu:
[8, 1, 14, 16, 6, 13, 9, 7, 11, 1, 18, 1, 17, 9, 3, 12, 4, 4, 11, 13]

Mảng sau khi đổi dấu (các số từ 9 đến 15):
[8, 1, -14, 16, 6, -13, -9, 7, -11, 1, 18, 1, 17, -9, 3, -12, 4, 4, -11, -13]


In [ ]:
#9
matrix = [[random.randint(10, 21) for _ in range(4)] for _ in range(3)]

print("Ma trận 3x4:")
for row in matrix:
    print(row)

Ma trận 3x4:
[10, 21, 16, 18]
[19, 16, 14, 12]
[15, 15, 10, 13]


In [ ]:
#10
n = 10
matrix = []

for i in range(n):
    row = []
    for j in range(n):
        if i == 0 or i == n-1 or j == 0 or j == n-1:
            row.append(1)
        else:
            row.append(0)
    matrix.append(row)

print("Ma trận 10x10:")
for row in matrix:
    print(*row)

Ma trận 10x10:
1 1 1 1 1 1 1 1 1 1
1 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 1
1 0 0 0 0 0 0 0 0 1
1 1 1 1 1 1 1 1 1 1


In [ ]:
import tensorflow as tf

In [ ]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
print(r1)
r1_float = tf.cast(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('hello', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'hello', shape=(), dtype=string)


In [ ]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
rank_2_tensor = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29]],])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29]],])
print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:',rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


In [ ]:
#1 Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0
tensor = np.zeros((2, 3))
print(tensor)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#2 Cho X = [[1, 2, 3], [4, 5, 6]], hãy tạo tensor có kích thước và dtype như X với các phần tử được gán 0
X = np.array([[1, 2, 3], [4, 5, 6]])
tensor = np.zeros_like(X)
print(tensor)

[[0 0 0]
 [0 0 0]]


In [ ]:
#3 Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5
tensor = np.full((3, 2), 5)
print(tensor)

[[5 5]
 [5 5]
 [5 5]]


In [ ]:
#4 Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]
even_numbers = [6, 8, 10]
tensor = np.random.choice(even_numbers, size=50)
print(tensor)

[ 6  8  8  8  8  6  8 10  6  6 10 10  6  6  6 10  6  8  6  6  8  6  8 10
  6  8 10  8  8  6  8  6 10 10  8  8 10  8  8  6 10  8 10  6 10  6  8  8
  6  8]


In [ ]:
#5 Tạo một tensor 1-chiều có giá trị như [10, 12, 14, …, 100]
tensor = np.arange(10, 101, 2)
print(tensor)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


In [ ]:
#6 Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối normal với mean=0, standard deviation = 2
tensor = np.random.normal(loc=0, scale=2, size=(3, 2))
print(tensor)

[[-3.16536158  3.69307985]
 [-0.22623048 -4.04112974]
 [ 3.61716534 -4.31561389]]


In [ ]:
#7 Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối uniform trong phạm vi [0, 2]
tensor = np.random.uniform(0, 2, (3, 2))
print(tensor)

[[1.13755284 1.79177838]
 [1.4252959  1.35412732]
 [1.58278943 0.14222697]]


In [ ]:
#8 Cho tensor X = [[1, 2], [3, 4], [5, 6]]. Hãy shuffle X theo chiều thứ nhất (sử dụng random_shuffle)
X = np.array([[1, 2], [3, 4], [5, 6]])
np.random.shuffle(X)
print(X)

[[1 2]
 [5 6]
 [3 4]]


In [ ]:
#9 Hãy tạo ngẫu nhiên tensor kích thước (10, 10, 3). Cắt thành tensor có kích thước (5, 5, 3) (sử dụng random_crop)
X = np.random.rand(10, 10, 3)
crop_h, crop_w = 5, 5

start_h = np.random.randint(0, 10 - crop_h + 1)
start_w = np.random.randint(0, 10 - crop_w + 1)

cropped = X[start_h:start_h+crop_h, start_w:start_w+crop_w, :]

print("Shape ban đầu:", X.shape)
print("Shape sau crop:", cropped.shape)

Shape ban đầu: (10, 10, 3)
Shape sau crop: (5, 5, 3)


In [ ]:
#10 Tạo ngẫu nhiên hai tensor 1-chiều x, y có 5 phần tử. Trả về x + y nếu x < y, và x – y nếu x > y
x = np.random.randint(0, 10, 5)
y = np.random.randint(0, 10, 5)

print("x:", x)
print("y:", y)

result = np.where(x < y, x + y, x - y)

print("Kết quả:", result)

x: [7 5 4 1 2]
y: [8 6 5 0 5]
Kết quả: [15 11  9  1  7]
