<a href="https://colab.research.google.com/github/MinhPhuong41/DL1/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
my_list = [1, 9, 15, 39]
print(my_list)
my_number_arry = np.array(my_list)
print(my_number_arry)

[1, 9, 15, 39]
[ 1  9 15 39]


In [ ]:
c = np.array([(1, 2, 3),
              (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n',e)
print('One matrix: \n',f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print(g)
print(g.shape)
h = g.reshape(3,4)
print('reshape (3,4)\n', h)
j = g.reshape(3,2,2)
print('reshape (3,2,2)\n', j)
k = g.reshape(2,3,2)
print('reshape (2,3,2)\n', j)


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [ ]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [ ]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print(h_stack)
v_stack = np.vstack((f, g))
print(v_stack)


[1. 2. 3. 4. 5. 6.]
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
a = np.random.randint(100, size=(5,))
print('Random 1-D arry\n',a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D arry\n',b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D arry\n',c)

Random 1-D arry
 [69 63 17 32 91]
Random 2-D arry
 [[54 33 61 79]
 [63  2 85 21]
 [35 96 16 51]]
Random 3-D arry
 [[[48 36 59]
  [81  5 43]
  [10 59  6]
  [37 77 58]]

 [[22 66 59]
  [ 5 21 44]
  [ 9  6 75]
  [39 74 45]]

 [[ 0 90 50]
  [ 4 50  9]
  [75  6 22]
  [62 10 50]]]


In [ ]:
a = np.random.rand(5)
print('Random 1-D arry\n',a)
b = np.random.rand(3, 4)
print('Random 2-D arry\n',b)
c = np.random.rand(3, 4, 3)
print('Random 3-D arry\n',c)

Random 1-D arry
 [0.03565416 0.70404085 0.43760935 0.32210546 0.83811733]
Random 2-D arry
 [[0.58253658 0.59771405 0.46856771 0.1748403 ]
 [0.58893033 0.42117073 0.32136074 0.50419273]
 [0.17648801 0.83264528 0.10973859 0.72116543]]
Random 3-D arry
 [[[0.23113484 0.20812784 0.7846501 ]
  [0.1339713  0.04624077 0.51994628]
  [0.70420641 0.81265273 0.43675805]
  [0.15866539 0.29636253 0.19397648]]

 [[0.37401141 0.20271806 0.73707799]
  [0.39485511 0.19469309 0.05813355]
  [0.45914726 0.69714345 0.7408849 ]
  [0.28366681 0.42126893 0.85676072]]

 [[0.03516617 0.62003829 0.35079401]
  [0.43914611 0.44017161 0.02969609]
  [0.29013834 0.44110616 0.81172323]
  [0.86753313 0.40564743 0.50266332]]]


In [ ]:
a  = np.random.normal(5, 0.5, 10)
print(a)

[5.37804191 4.64016416 5.43655824 4.97777752 4.94461534 4.75711404
 5.36325193 5.26109348 4.55120696 3.86312168]


In [ ]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)


4
[[14  2  8 20  6]
 [ 6 16 14 10  8]
 [18 16  6  2 12]]


In [ ]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n',A)
np.array(A)[2] = 2
print('Third row with arry\n', A)
np.asarray(A)[2] = 2
print('Third row with asarry\n', A)


The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Third row with arry
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Third row with asarry
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.arange(1, 20)
print(a)
b = np.arange(1, 20, 2)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
a = np.linspace(1., 5., num=10)
print(a)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
print('second column:', a[:,1])
print('first column:', a[:,0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


In [ ]:
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [ ]:
h = np.array([[1, 2], [3,4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n',df_h)
numpy_h = np.array(df_h)
print('Numpy array:\n',numpy_h)



DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [ ]:
dic = {'Name':['John','Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [ ]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3','so4'])
print(df.head())

        so1       so2       so3       so4
0 -0.382927 -1.105155 -0.146865  0.305810
1 -0.108774  0.800689 -0.984880  1.300713
2  1.258461  1.443931 -1.312656  0.994993
3  0.465898  0.260265 -1.218706  0.059964
4 -0.590875 -0.509637 -0.262758  0.547994


In [ ]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3','so4'])
print(df.head())
print("Cot so1\n",df['so1'])
print("Nhieu dong\n",df[0:3])
print("Nhieu cot\n",df[['so1','so3']])
print("Nhieu dong, nhieu cot\n", df.iloc[:3, :2])
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0  0.212752  0.072560  0.040365 -0.441771
1 -0.683566 -0.730853  0.088702 -0.666464
2  0.068089  1.162581 -0.702441  0.526618
3  2.325648  0.103077 -0.277613 -1.652056
4 -1.603717  0.374625  0.971074  1.565192
Cot so1
 0     0.212752
1    -0.683566
2     0.068089
3     2.325648
4    -1.603717
5     0.201287
6    -0.245871
7     1.090676
8     1.721483
9    -1.168429
10   -0.567842
11   -1.485043
12   -1.263294
13    0.060359
14    0.562228
15    0.090721
16    0.842798
17   -1.346410
18    0.280524
19   -1.388706
Name: so1, dtype: float64
Nhieu dong
         so1       so2       so3       so4
0  0.212752  0.072560  0.040365 -0.441771
1 -0.683566 -0.730853  0.088702 -0.666464
2  0.068089  1.162581 -0.702441  0.526618
Nhieu cot
          so1       so3
0   0.212752  0.040365
1  -0.683566  0.088702
2   0.068089 -0.702441
3   2.325648 -0.277613
4  -1.603717  0.971074
5   0.201287  1.566221
6  -0.245871  1.072150
7   1.090676 -1.900547
8   1.721483 -1

In [ ]:
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]}, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]}, index=[3, 4])
df_concat = pd.concat([df1, df2])
print(df_concat)
#Xoa Name trung
print(df_concat.drop_duplicates('Name'))
#Sap xep theo cot Age
print(df_concat.sort_values('Age'))
#Doi ten cot
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print(df_rename)

    Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
    Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
    Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
  Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [ ]:
path = '/content/sample_data/salary_data.csv'
COLUMNS = ['YearsExperience', 'Salary']
df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)
df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)


   YearsExperience    Salary
0  YearsExperience    Salary
1              1.1  39343.00
2              1.3  46205.00
3              1.5  37731.00
4              2.0  43525.00
(31, 2)
   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
(30, 2)


In [ ]:
path = '/content/sample_data/Fish.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())
print(df_csv.groupby(['Species']).mean().head())
print(df_csv.groupby(['Species'])['Weight'].min().head())
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
             Weight    Length1    Length2    Length3     Height     Width
Species                                                                  
Bream    617.828571  30.305714  33.108571  38.354286  15.183211  5.427614
Parkki   154.818182  18.727273  20.345455  22.790909   8.962427  3.220736
Perch    382.239286  25.735714  27.892857  29.571429   7.861870  4.745723
Pike     718.705882  42.476471  45.482353  48.717647   7.713771  5.086382
Roach    152.050000  20.645000  22.275000  24.970000   6.694795  3.657850
Species
Bream     242.0
Parkki     55.0
Perch       5.9
Pike      200.0
Roach       0.0
Name: Weight, dtype: f

In [ ]:
#1
arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên 3x3:")
print(arr)
print("-" * 30)
check_nonzero = np.all(arr != 0)
print("Tất cả các phần tử có khác 0 không:", check_nonzero)

Mảng ngẫu nhiên 3x3:
[[ 5  0  4]
 [ 2  3  8]
 [20  8  7]]
------------------------------
Tất cả các phần tử có khác 0 không: False


In [ ]:
#2
arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên 3x3:")
print(arr)
print("-" * 30)
check_any_nonzero = np.any(arr != 0)
print("Có phần tử nào khác 0 không:", check_any_nonzero)

Mảng ngẫu nhiên 3x3:
[[16 19  0]
 [15  6 15]
 [19  4 20]]
------------------------------
Có phần tử nào khác 0 không: True


In [ ]:
#3
# --- TRƯỜNG HỢP 1: MẢNG 1 CHIỀU ---
print("--- SO SÁNH MẢNG 1 CHIỀU ---")
a1 = np.array([10, 20, 30, 40])
b1 = np.array([15, 20, 25, 45])
print("Mảng a1: {a1}")
print("Mảng b1: {b1}")
print("a1 > b1  (greater):      ", np.greater(a1, b1))
print("a1 >= b1 (greater_equal):", np.greater_equal(a1, b1))
print("a1 < b1  (less):         ", np.less(a1, b1))
print("a1 <= b1 (less_equal):   ", np.less_equal(a1, b1))
# --- TRƯỜNG HỢP 2: MẢNG 2 CHIỀU (3x3) ---
print("\n--- SO SÁNH MẢNG 2 CHIỀU (3x3) ---")
# Tạo 2 mảng ngẫu nhiên để so sánh
a2 = np.random.randint(0, 10, size=(3, 3))
b2 = np.random.randint(0, 10, size=(3, 3))
print("Mảng a2:\n", a2)
print("Mảng b2:\n", b2)

print("\nKết quả greater (a2 > b2):")
print(np.greater(a2, b2))

print("\nKết quả greater_equal (a2 >= b2):")
print(np.greater_equal(a2, b2))

print("\nKết quả less (a2 < b2):")
print(np.less(a2, b2))

print("\nKết quả less_equal (a2 <= b2):")
print(np.less_equal(a2, b2))




--- SO SÁNH MẢNG 1 CHIỀU ---
Mảng a1: {a1}
Mảng b1: {b1}
a1 > b1  (greater):       [False False  True False]
a1 >= b1 (greater_equal): [False  True  True False]
a1 < b1  (less):          [ True False False  True]
a1 <= b1 (less_equal):    [ True  True False  True]

--- SO SÁNH MẢNG 2 CHIỀU (3x3) ---
Mảng a2:
 [[0 7 2]
 [9 4 4]
 [9 5 9]]
Mảng b2:
 [[2 7 7]
 [5 5 7]
 [9 0 1]]

Kết quả greater (a2 > b2):
[[False False False]
 [ True False False]
 [False  True  True]]

Kết quả greater_equal (a2 >= b2):
[[False  True False]
 [ True False False]
 [ True  True  True]]

Kết quả less (a2 < b2):
[[ True False  True]
 [False  True  True]
 [False False False]]

Kết quả less_equal (a2 <= b2):
[[ True  True  True]
 [False  True  True]
 [ True False False]]


In [ ]:
#4
ones = np.ones(10, dtype=int) # Tạo mảng gồm 10 số 1
zeros = np.zeros(10, dtype=int) # Tạo mảng gồm 10 số 0
fives = np.full(10, 5, dtype=int) # Tạo mảng gồm 10 số 5

# Nối các mảng lại với nhau
combined_array = np.concatenate((zeros , ones, fives))

print(combined_array)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


In [ ]:
#5
even_array = np.arange(30, 71, 2)

print("Mảng số nguyên chẵn từ 30 đến 70:")
print(even_array)

Mảng số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
